### PR TITLE
Fix Clang warning with __builtin_assume

### PR DESCRIPTION
**Pull request by iomaganaris**
Building the project with `Clang` generates the following warning:
```
the argument to '__builtin_assume' has side effects that will be discarded [-Wassume]
```

Seems like Clang doesn't handle the hint well unless we pass a const/pure attribute to the function call inside the assume. See: https://github.com/llvm/llvm-project/issues/55636 and https://github.com/llvm/llvm-project/pull/93077

With this change performance for the fn fused nabla examples is significantly improved on clang-cuda and is now much faster than (our old) nvcc, which doesn't have `assume` support.

### CODE REVIEW

**Comment by iomaganaris** [comment]
launch jenkins

**Comment by iomaganaris** [comment]
launch perftests

**Review by fthaler — APPROVED** [review]

**Comment by iomaganaris** [comment]
launch jenkins

**Comment by iomaganaris** [comment]
launch perftests

**Comment by iomaganaris** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
does it have any effect on perftests? if not, we can merge.

**Comment by fthaler** [comment]
> does it have any effect on perftests? if not, we can merge.

Looks like: https://jenkins-mch.cscs.ch/job/GridTools/job/GridTools_perftest_PR/326/env=cray,label=daint-cn/Results/
But not sure if it is up to date with master references.

**Comment by fthaler** [comment]
launch perftest

**Pull request merged**
