### PR TITLE
CMake + Jenkins: add c++17 testing

### PR DESCRIPTION
**Pull request by havogt**
Add cray_cxx_17 environment which enables C++17 for tests.

Unrelated:
- Improve testing setup for examples, they nearly work with Cray except for #1575

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Review by fthaler — APPROVED** [review]

**Review by anstaf — APPROVED** [review]

**Pull request merged**
