### PR TITLE
Set accessor dimension default based on provided extent

### PR DESCRIPTION
**Pull request by anstaf**
- the default number of dimensions for an accessor is deduced from the provided extent now
- accessor ctor accepts any number of offsets; in debug build it is checked that offsets in the dimensions that are greater than accessor dimension number are set to zero; in the release build those offsets are ignored;
- accessor extents in tridiagonal solver are fixed to reflect the actual used offsets 
- `dimension` ctors are cleaned up.
- `at_key_with_default` function is introduced in `hymap` API
- `flx` and `fly` functors in horizontal diffusion are rewritten to use tmp variable instead of out argument
- `ICC` tunings is `accessor_base` implementation are removed

### CODE REVIEW

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
perftest is OK

**Comment by havogt** [comment]
It looks like we should update the reference. There is some performance improvement for x86 and also for horizontal diffusion on kesch cuda float. (+ changes for icc)

**Pull request merged**
