### PR TITLE
Improved Data Layout for Neighbor Tables

### PR DESCRIPTION
**Pull request by fthaler**
Uses unit stride in location dimension (SoA layout) instead of array-of-tuple (AoS layout) in the fn nabla tests.

### CODE REVIEW

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch jenkins

**Comment by havogt** [comment]
launch perftests

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Comment by havogt** [comment]
Was there any difference in the end? Can you add a comment in the PR description how performance changed.

**Pull request merged**
