### PR TITLE
Workaround against new gtest

### PR DESCRIPTION
**Pull request by anstaf**

### CODE REVIEW

**Review by havogt — COMMENTED** [review]
You prefer this solution over a 10 line pure C++ patch?

**Comment by anstaf** [comment]
> You prefer this solution over a 10 line pure C++ patch?

Yes. After gtest 1.11 release it is clear that the contract is that it should be at least one type in the test suite.
I don't like the idea of the patch. We will have to recreate it after each gtest release.
The current solution looks more reliable.

**Comment by anstaf** [comment]
By the way, most of the code in the PR is just beautifying the current API (factoring out all gtest details over the facade of our macros).
I can split this PR into two: 1. improving interface; 2. adapting to gtest 1.11.
In this case the second part will be also about 10 lines.

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch perftest

**Review by havogt — APPROVED** [review]

**Pull request merged**
