### PR TITLE
Cpu reduction

### PR DESCRIPTION
**Pull request by anstaf**
add `cpu` backend to reduction framework

### CODE REVIEW

**Comment by anstaf** [comment]
launch jenkins

**Comment by anstaf** [comment]
launch jenkins

**Comment by anstaf** [comment]
launch jenkins

**Review by fthaler — APPROVED** [review]

**Comment by anstaf** [comment]
launch jenkins

**Comment by anstaf** [comment]
launch jenkins

**Comment by anstaf** [comment]
launch jenkins

**Pull request merged**
