### PR TITLE
Remove ldg_ptr and Replace Functionality by const_ptr_deref

### PR DESCRIPTION
**Pull request by fthaler**
No performance change in the GridTools performance tests visible, however this might change performance of external code that does not rely on GridTools storages but uses `sid::composite` or `sid::dimension_to_tuple_like` which now use `__ldg` but previously did not.

### CODE REVIEW

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Review by havogt — APPROVED** [review]

**Pull request merged**
