### PR TITLE
Daint upgrade 2022-02-16: new performance references

### PR DESCRIPTION
**Pull request by havogt**
Cray clang version 11.0.0 -> Cray clang version 12.0.3

Cray (with clang-cuda) shows mostly quite big performance improvements, often on par with nvcc. Also, cpu performance is improved; in many cases quite significantly (probably because auto-vectorization started working).
Other compiler have minor fluctuations.

### CODE REVIEW

**Comment by havogt** [comment]
lauch perftests

**Comment by havogt** [comment]
launch perftests

**Comment by fthaler** [comment]
launch perftest

**Review by fthaler — APPROVED** [review]

**Comment by havogt** [comment]
launch jenkins

**Pull request merged**
