### PR TITLE
Daint: change cuda module

### PR DESCRIPTION
**Pull request by havogt**
Environment changes on daint:
- CUDA is now loaded as `cudatoolkit` instead of a specific version
- Cray clang is now used without `-fno-cray`. `-fno-cray` doesn't work currently and is tracked here https://webrt.cscs.ch/Ticket/Display.html?id=40241. A Cray ticket is filed.
However, the `test_hugepage_alloc` fails, which looks like an invalid optimization, see #1557.

Performance changes:
We see quite some chagnes both on GPU and CPU after the upgrade.
Most significant:
- CUDA: vertical advection on small domain with float is about 40% slower (in all variants: clang-cuda, nvcc-clang, nvcc-gcc)
- cpu_kfirst: factor 10x slowdown for layout_transformation, maybe a vectorization issue

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch perftest

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch perftest

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch perftest

**Review by fthaler — APPROVED** [review]

**Pull request merged**
