### PR TITLE
CI: new path to boost and venvs

### PR DESCRIPTION
**Pull request by havogt**

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Comment by havogt** [comment]
launch perftests

**Comment by havogt** [comment]
launch jenkins

**Pull request merged**
