### PR TITLE
More SID changes

### PR DESCRIPTION
**Pull request by anstaf**

### CODE REVIEW

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
do perftest

**Comment by lukasm91** [comment]
@anstaf Is there a reason why we are still adding stuff to this PR? Didn't we aim for creating a branch out of this and merging PRs into that? I mentioned this already several times and we all agreed that this PR should be merged ASAP - there is absolutely no way that we can ever review this, and we should stop this mode immediately, because it should be more than one person knowing what's going on in stencil-composition...
Can we stop new development here immediately and merge it into a branch right after fixing the current issues?

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
do perftest

**Pull request closed without merging**
