### PR TITLE
CMake cleanup

### PR DESCRIPTION
**Pull request by lukasm91**
- Remove not needed components (we have only 1 compiled component...)
- Unify formatting (tab = 4 spaces, not  2; no spaces inside parenthesis)

### CODE REVIEW

**Comment by lukasm91** [comment]
launch strgrid

**Comment by lukasm91** [comment]
launch strgrid

**Comment by lukasm91** [comment]
launch strgrid

**Comment by havogt** [comment]
launch strgrid

**Comment by havogt** [comment]
launch icgrid

**Comment by havogt** [comment]
launch mpistrgrid

**Comment by havogt** [comment]
launch perftest

**Pull request merged**
