### PR TITLE
Introduce GT_DEFINE_ACCESSORS macro

### PR DESCRIPTION
**Pull request by anstaf**
`GT_DEFINE_ACCESSORS` macro is introduced to reduce the boilerplate in accessors definitions.
All stencil functors in the codebase are modified to use the macro

### CODE REVIEW

**Comment by havogt** [comment]
launch strgrid

**Comment by havogt** [comment]
launch icgrid

**Comment by havogt** [comment]
launch perftest

**Comment by havogt** [comment]
testing jenkins...

**Comment by anstaf** [comment]
launch strgrid

**Pull request closed without merging**
