### PR TITLE
CI: Update modules for GT v2.0

### PR DESCRIPTION
**Pull request by havogt**
Passes all setups except ault-hip.

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
tests ok (I cancelled dom as it was taking long).

**Review by fthaler — APPROVED** [review]

**Pull request merged**
