### PR TITLE
Use ‘const’ in Neighbor Table Value Types

### PR DESCRIPTION
**Pull request by fthaler**
Additionally fixes missing `host_view` etc. in const data stores. Gives speedups when combined with #1795.

### CODE REVIEW

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Review by havogt — COMMENTED** [review]
Let's talk about the changes in data_store next week.

**Review by havogt — APPROVED** [review]

**Pull request merged**
