### PR TITLE
Getting started: Remove unnecessary settings

### PR DESCRIPTION
**Pull request by havogt**

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
tsa was not available when this run, rest is green.

**Comment by fthaler** [comment]
I am 100% sure that you kill HIP-compatibility if you remove those ;)
HIP requires -std=c++XX instead of -std=gnu++XX as gnu++ enables 128-bit floats, triggering a complain about GPU incompatibility even if we don’t use them (maybe it works with the newest versions of HIP, I should fix Ault tests at some point)…

**Comment by havogt** [comment]
Ok, I'll add a comment instead.

**Comment by havogt** [comment]
launch jenkins

**Pull request merged**
