### PR TITLE
Example for type erasure

### LINKED ISSUE #1294: Doc: explain computation<> type-erasure and how to use it
The documentation doesn't mention how to use the type-erased computation, e.g. to hold a computation as a member of a class.

We should also add a note that `make_computation` should not be used in headers because of compile-time explosion.

### PR DESCRIPTION
**Pull request by lukasm91**
Fixes #1294

### CODE REVIEW

**Comment by lukasm91** [comment]
launch strgrid

**Comment by lukasm91** [comment]
launch strgrid

**Comment by lukasm91** [comment]
launch strgrid

**Comment by lukasm91** [comment]
launch icgrid

**Comment by havogt** [comment]
Could you also add a small paragraph in the documentation explaining when and why to apply this pattern and a pointer to the example?

**Comment by lukasm91** [comment]
paragraph added

**Pull request merged**
