### PR TITLE
Fixes for HIP + OpenMP Compilation and Ault Testing Env

### PR DESCRIPTION
**Pull request by fthaler**

### CODE REVIEW

**Comment by fthaler** [comment]
launch jenkins

**Review by havogt — APPROVED** [review]

**Comment by havogt** [comment]
I'll enable ault for PR testing and re-launch.

**Comment by havogt** [comment]
Disabled. I forgot that 2 tests are failing, see issue #1576

**Comment by havogt** [comment]
launch jenkins

**Pull request merged**
