### PR TITLE
Replace if-Conditions by Ternary Operators in Nabla

### PR DESCRIPTION
**Pull request by fthaler**
The unconditional shifts (unconditional loads from neighbor tables) seem to help NVCC’s load hoisting and loop-invariant code motion in the case of k-blocking. Increases performance by up to 8% on double precision  and up to 2.5% on single precision fused nabla implementations.

### CODE REVIEW

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Review by havogt — APPROVED** [review]
we should look into gt4py codegen if these changes are relevant there

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Pull request merged**
