### PR TITLE
Updated References

### LINKED ISSUE #1689: CI: Enable perftests for nvcc_cray
and add reference

### PR DESCRIPTION
**Pull request by fthaler**
Includes up-to-date performance references for the current Jenkins setup. Fixes #1689

### CODE REVIEW

**Comment by fthaler** [comment]
launch perftest

**Review by havogt — COMMENTED** [review]
Where there any performance changes in the 2 existing setups?

**Comment by fthaler** [comment]
Not really, just minor CPU fluctuations. Those are the results (from running PR #1690):
https://jenkins-mch.cscs.ch/job/GridTools_perftest_PR/239/env=cray,label=daint-cn/Results/
https://jenkins-mch.cscs.ch/job/GridTools_perftest_PR/239/env=nvcc_gcc,label=daint-cn/Results/

**Comment by fthaler** [comment]
But I just noticed that the previous references are from yesterday, so does not say much apart from more or less stable results… Should I remove the unneeded updates? In essence, only nvcc_cray needs to be included then.

**Comment by havogt** [comment]
Hmm. Actually I should have put a comment yesterday that performance was more or less unaffected. Maybe you can mention here, that there were only minor fluctuations in this and the last update.

**Review by havogt — APPROVED** [review]
Please add comment that performance for daint_cray and daint_nvcc_gcc only had fluctuations in this and the previous reference update.

**Pull request merged**
