### PR TITLE
introduce const_ref

### PR DESCRIPTION
**Pull request by anstaf**
todo

### CODE REVIEW

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
do perftest

**Comment by anstaf** [comment]
launch strgrid

**Comment by anstaf** [comment]
launch icgrid

**Comment by anstaf** [comment]
do perftest

**Comment by lukasm91** [comment]
Dycore: Performance OK, Validation OK.

**Pull request closed without merging**
