### PR TITLE
Fix for PyUtils

### PR DESCRIPTION
**Pull request by fthaler**
Last PyUtils commit killed perftests.

### CODE REVIEW

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
do perftest

**Comment by fthaler** [comment]
launch strgrid

**Comment by havogt** [comment]
launch perftest

**Comment by havogt** [comment]
launch strgrid

**Comment by havogt** [comment]
launch perftest

**Comment by havogt** [comment]
launch perftest

**Pull request merged**
