### PR TITLE
More Inlining in cpu_kfirst Backend

### PR DESCRIPTION
**Pull request by fthaler**
Significantly improves performance in some GT4Py benchmarks.

### CODE REVIEW

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
Does not bring relevant speedup.

**Comment by fthaler** [comment]
launch perftest

**Comment by havogt** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch perftests

**Comment by havogt** [comment]
launch jenkins

**Review by havogt — APPROVED** [review]

**Comment by havogt** [comment]
tests look ok, random failures due to daint instabilities.

**Review by havogt — APPROVED** [review]
Let's merge this before Felix is back. ;)

**Pull request merged**
