### PR TITLE
Add Missing fn_unstructured_nabla_fused_tuple_of_fields to Regression & Performance Tests

### PR DESCRIPTION
**Pull request by fthaler**

### CODE REVIEW

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch perftest

**Comment by fthaler** [comment]
launch jenkins

**Comment by fthaler** [comment]
launch perftest

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
Interestingly, again, on a large domain tuple of field vs field of tuple is not different.

**Review by havogt — APPROVED** [review]

**Pull request merged**
