### PR TITLE
Bug: storage/gpu.h functions within __CUDA_ARCH__

### PR DESCRIPTION
**Pull request by havogt**
not sure why this should be inside an `#if defined(GT_CUDA_ARCH)`

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
probably replaces #1776

**Review by iomaganaris — APPROVED** [review]

**Comment by havogt** [comment]
launch perftests

**Pull request merged**
